version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres # Replace with your password
      POSTGRES_DB: testWad             # Optional: Specify a database name
      POSTGRES_USER: postgres          # Optional: Specify a user (default is postgres)
    ports:
      - "61111:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Optional: Persistent storage

volumes:
  postgres_data:
